#!/bin/env perl
use warnings FATAL => 'all';
use strict;
use Cfm::Cli;
use Cfm::Common::Logging;

binmode STDOUT, ":utf8";

my $logger = Cfm::Common::Logging->setup_logger;
$logger->info('
 ______  ______ __    __
/\  ___\/\  ___/\ "-./  \
\ \ \___\ \  __\ \ \-./\ \
 \ \_____\ \_\  \ \_\ \ \_\
  \/_____/\/_/   \/_/  \/_/  (c) Constantin Weisser, 2017

'
);
$logger->info("Starting CLI ...");
my $cli = Cfm::Cli->new;
$cli->run;
$logger->info("Application is terminating normally.");
exit 0;
